# Perceptron de Uma Camada

In [1]:
import tensorflow as tf
import numpy as np

Atributos previsores:

In [3]:
X = np.array([[0.0, 0.0],[0.0, 1.0],[1.0, 0.0],[1.0, 1.0]])
print(X)

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]


Respostas/saídas:

In [4]:
y = np.array([[0.0],[0.0],[0.0],[1.0]])
print(y)

[[0.]
 [0.]
 [0.]
 [1.]]


Matriz com os pesos:

In [7]:
W = tf.Variable(tf.zeros([2,1], dtype=tf.float64))
type(W)
print(W)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float64, numpy=
array([[0.],
       [0.]])>


## 1ª Parte: Multiplicação e soma das entradas pelos Pesos

In [9]:
camada_saida = tf.matmul(X, W)
print(camada_saida)

tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]], shape=(4, 1), dtype=float64)
