<a href="https://colab.research.google.com/github/diegogrr/UdemyTF/blob/master/tensorflowSiteTuto/TensorFlow_2_quickstart_for_beginners.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow 2 quickstart for beginners

Download and install TensorFlow 2. Import TensorFlow into your programa.

In [0]:
import tensorflow as tf

Load and prepare the MNIST dataset. Convert the samples from integers to floating-point numbers:

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 0s 0us/step


Build the tf.keras.Sequential model by stacking layers. Choose an optimizer and loss function for training:

In [0]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

For each example the model returns a vector of "logits" or "log-odds" scores, one for each class.

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.52974784,  0.43318248, -0.08779633, -0.32937235, -0.44906488,
         0.05893646, -0.17824127,  0.7367997 ,  0.17765346, -0.643388  ]],
      dtype=float32)

WARNING:tensorflow:Layer flatten is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because it's dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

The tf.nn.softmax function converts these logits to "probabilities" for each class: 

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.15137081, 0.1374372 , 0.08162931, 0.06411076, 0.05687864,
        0.09453037, 0.07457038, 0.18619311, 0.10644603, 0.0468334 ]],
      dtype=float32)

The losses.SparseCategoricalCrossentropy loss takes a vector of logits and a True index and returns a scalar loss for each example.

In [0]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

This loss is equal to the negative log probability of the true class: It is zero if the model is sure of the correct class.

This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to -tf.log(1/10) ~= 2.3.

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.3588343

In [0]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

The Model.fit method adjusts the model parameters to minimize the loss: 

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2997 - accuracy: 0.9119
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1462 - accuracy: 0.9568
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1096 - accuracy: 0.9670
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0875 - accuracy: 0.9727
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0745 - accuracy: 0.9767


The Model.evaluate method checks the models performance, usually on a "Validation-set" or "Test-set".

In [11]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0843 - accuracy: 0.9734


[0.08433713018894196, 0.9733999967575073]

The image classifier is now trained to ~98% accuracy on this dataset. To learn more, read the TensorFlow tutorials.

If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:

In [0]:
probability_model = tf.keras.Sequential([
                                         model,
                                         tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[9.0911101e-09, 3.0621770e-09, 2.5931172e-07, 1.4409870e-04,
        2.1352102e-12, 3.3452335e-07, 5.6444374e-15, 9.9985456e-01,
        3.1309476e-08, 6.3291924e-07],
       [3.5259481e-07, 2.7602327e-06, 9.9993336e-01, 5.4760585e-05,
        7.0137356e-15, 3.7067550e-06, 2.4304763e-06, 2.9919448e-13,
        2.6229989e-06, 5.2041813e-14],
       [1.0230884e-07, 9.9930441e-01, 8.7272325e-05, 6.8596901e-06,
        3.4057755e-06, 1.3926494e-05, 9.0867634e-06, 5.2816333e-04,
        4.6728168e-05, 1.3828559e-07],
       [9.9991751e-01, 2.7855498e-09, 1.4893377e-05, 5.2933649e-07,
        6.3341048e-08, 8.6389809e-06, 5.3949730e-05, 2.3972500e-06,
        1.0873260e-06, 8.1400930e-07],
       [9.8349301e-06, 2.7670675e-08, 5.2338382e-06, 1.5344511e-07,
        9.8944396e-01, 2.0396112e-06, 9.1078027e-06, 1.0111441e-03,
        8.7005192e-06, 9.5097870e-03]], dtype=float32)>