# Multiplicação de Matrizes

O produto de uma matriz por outra não é determinado por meio do produto dos seus respectivos elementos.

Assim, o produto das matrizes A = $(a_{ij})_{m x p}$  e B = $(b_{ij})_{p x n}$ é a matriz C = $(c_{ij})_{m x n}$, em que cada elemento **$c_{ij}$** é obtido por meio da soma dos produtos dos elementos correspondentes da i-ésima linha de A pelos elementos da j-ésima coluna B.

Vamos multiplicar as matrizes ![alt text](https://www.somatematica.com.br/emedio/matrizes/Image32.gif) para entender como se obtém cada elemento $c_{ij}$.



*   1ª linha e 1ª coluna 

![alt text](https://www.somatematica.com.br/emedio/matrizes/Image31.gif)
*   1ª linha e 2ª coluna

![alt text](https://www.somatematica.com.br/emedio/matrizes/Image33.gif)
*   2ª linha e 1ª coluna

![alt text](https://www.somatematica.com.br/emedio/matrizes/Image34.gif)
*   2ª linha e 2ª coluna

![alt text](https://www.somatematica.com.br/emedio/matrizes/Image35.gif)

Assim, 

![alt text](https://www.somatematica.com.br/emedio/matrizes/Image36.gif)

Fonte: https://www.somatematica.com.br/emedio/matrizes/matrizes4.php


In [0]:
#importação do Tensorflow
import tensorflow as tf

Criação das matrizes. Vamos utilizar os mesmo valores do exemplo acima.

In [6]:
a = tf.constant([[ 1, 2], [3, 4]])
b = tf.constant([[-1, 3], [4, 2]])
print(a.numpy())
print(b.numpy())

[[1 2]
 [3 4]]
[[-1  3]
 [ 4  2]]


## tf.matmul()
matrix multiplication

Método utilizado para realizar a **multiplicação** de matrizes.

In [4]:
multiplicacao = tf.matmul(a, b)
print(multiplicacao.numpy())

[[ 7  7]
 [13 17]]


Se para a multiplicação de matrizes for utilizado o operador '*', o resultado será diferente a do obtido pelo método matmul(), pois a multiplicação ocorrerá entre os elementos de mesma posição na matriz. Esse resultado também está incorreta algebricamente.

In [5]:
print(a * b)

tf.Tensor(
[[-1  6]
 [12  8]], shape=(2, 2), dtype=int32)


O que ocorre se for invertida a ordem da multiplicação das matrizes?

O resultado é diferente, pois A.B é diferente de B.A:


In [7]:
multiplicacao2 = tf.matmul(b, a)
print(multiplicacao2.numpy())

[[ 8 10]
 [10 16]]


## Matrizes de ordem diferentes

![alt text](https://www.somatematica.com.br/emedio/matrizes/Image40.gif)

In [0]:
a1 = tf.constant([[2, 3], [0, 1], [-1, 4]])
b1 = tf.constant([[1, 2, 3], [-2, 0, 4]])

In [15]:
multiplicacao3 = tf.matmul(a1, b1)
print(a1.numpy(), '\n')
print(b1.numpy(), '\n')
print(multiplicacao3.numpy())

[[ 2  3]
 [ 0  1]
 [-1  4]] 

[[ 1  2  3]
 [-2  0  4]] 

[[-4  4 18]
 [-2  0  4]
 [-9 -2 13]]


Invertendo a ordem da multiplicação:

![alt text](https://www.somatematica.com.br/emedio/matrizes/Image44.gif)

In [16]:
multiplicacao3 = tf.matmul(b1, a1)
print(a1.numpy(), '\n')
print(b1.numpy(), '\n')
print(multiplicacao3.numpy())

[[ 2  3]
 [ 0  1]
 [-1  4]] 

[[ 1  2  3]
 [-2  0  4]] 

[[-1 17]
 [-8 10]]
