# Placeholders

Uma outra estrutura do TensorFlow, os placeholders, que faz parte da LowLevel API. De certa forma, é um tipo de variável na qual nós podemos atribuir dados. Ele não é inicializado e ele não contém os dados. Você defini qual o tipo de dados que ele recebe, e nós vamos deixar para passar esses dados mais tarde.

placeholder = espaço reservado

In [13]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
tf.__version__

Instructions for updating:
non-resource variables are not supported in the long term


'2.2.0'

## Primeiro placeholder

In [0]:
p = tf.placeholder('float', None) #(tipo de dado, dimensão)
# shape=(),pois não se sabe a dimensão desses dados, se será um escalar, uma matriz ou um vetor.
#p = tf.keras.Input(shape=(), dtype=tf.dtypes.float32)

In [0]:
operacao = p + 2


In [18]:
with tf.Session() as sess:
  resultado = sess.run(operacao, feed_dict = {p: [1, 2, 3]})
  print(resultado)

[3. 4. 5.]


In [0]:
p2 = tf.placeholder('float', [None, 5])
operacao2 = p2 * 5

In [21]:
with tf.Session() as sess:
  dados = [[1,2,3,4,5],[6,7,8,9,10]]
  resultado = sess.run(operacao2, feed_dict={p2: dados})
  print(resultado)

[[ 5. 10. 15. 20. 25.]
 [30. 35. 40. 45. 50.]]
