# Produto Escalar

Veremos como realizar a multiplicação e a soma utilizadas em um neurônio artificial. Mais especificamente, este representado pela imagem abaixo.

![alt text](https://dgbits.com.br/public/2020-05-14_11h30_47.png)

Importando o TensorFlow 2:

In [24]:
import tensorflow as tf
tf.__version__

'2.2.0'

Criação do vetor de entrada:

In [0]:
a = tf.constant([[-1.0, 7.0, 5.0]], name='entrada')

Representação dos pesos:

In [0]:
b = tf.constant([[0.8, 0.1, 0.0]], name='pesos')

Visualização dos valores:

In [27]:
print(a.numpy())
print()
print(b.numpy())

[[-1.  7.  5.]]

[[0.8 0.1 0. ]]


## Multiplicação

`.matmul()`: retornará um erro, pois as matrizes em questão não atendem as regras da álgebra linear para essa operação. Veja que o número de colunas de 'a' é diferente do número de linhas de 'b'.

Neste caso, então, teremos que usar um outro método que multiplica os elementos considerando apenas a sua posição na matriz/vetor.

`.multiply()`

In [28]:
multiplicacao = tf.multiply(a, b)
print(multiplicacao.numpy())

[[-0.8  0.7  0. ]]


## Somatório

Somatório da multiplicação.

`.reduce_sum()`: método para somar os elementos de uma matriz/vetor.

In [29]:
soma = tf.reduce_sum(multiplicacao)
print(soma.numpy())

-0.100000024


## Teste Adicional

Como os métodos `.multiply()` e `.reduce_sum()` se comportam em uma matriz com mais de uma linha?

Da mesma forma, pois consideram a posição que os elementos se encontram na matiz. Exemplo da multiplicação: $a_{11}$ x $b_{11}$; $a_{12}$ x $b_{12}$;...; $a_{21}$ x $b_{21}$...

In [30]:
c = tf.constant([[-1.0, 7.0, 5.0],[-1.0, 7.0, 5.0]])
d = tf.constant([[0.8, 0.1, 0.0],[0.8, 0.1, 0.0]])
print(c.numpy())
print()
print(d.numpy())
print()
multp = tf.multiply(c, d)
print(multp.numpy())
print()
soma2 = tf.reduce_sum(multp)
print(soma2.numpy())

[[-1.  7.  5.]
 [-1.  7.  5.]]

[[0.8 0.1 0. ]
 [0.8 0.1 0. ]]

[[-0.8  0.7  0. ]
 [-0.8  0.7  0. ]]

-0.20000005
