# Soma de Vetores e Matrizes

In [0]:
import tensorflow as tf

Vetores

In [0]:
a = tf.constant([9, 8, 7], name='a')
b = tf.constant([1, 2, 3], name='b')

Matrizes

In [22]:
a1 = tf.constant([[1, 2, 3], [4, 5, 6]], name='a1')
b1 = tf.constant([[1, 2, 3], [4, 5, 6]], name='b1')
type(a1)

tensorflow.python.framework.ops.EagerTensor

In [20]:
print(a1)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


Caso queira visualizar apenas as dimensões:

In [21]:
a1.shape

TensorShape([2, 3])

Matrizes com número de elementos diferentes.

In [29]:
a2 = tf.constant([[1, 2, 3], [4, 5, 6]])
b2 = tf.constant([[1], [2]])
print(a2.numpy())
print(b2.numpy())

[[1 2 3]
 [4 5 6]]
[[1]
 [2]]


## Soma de Vetores

Para que a soma de vetores e metrizes ocorra sem erros, é necessário que eles tenham o mesmo número de elementos.

In [0]:
soma = a + b

Observe que no TF2 a execução da soma acontece naturalmente. Não é necessário criar uma sessão para execução da "soma", como é no TF1.

In [15]:
print(soma)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


Observe que o tipo de cada cada um deles é o mesmo, inclusive da "soma".

In [16]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [17]:
type(b)

tensorflow.python.framework.ops.EagerTensor

In [18]:
type(soma)

tensorflow.python.framework.ops.EagerTensor

## Soma de Matrizes

Soma utilizando recursos do TF.


In [24]:
soma1 = tf.add(a1,b1)
print(soma1)

tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Que significa a mesma coisa que um somatório simples, utilizando o operador '+'.

In [25]:
print(a1 + b1)

tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


**Soma** de matrizes com **quantidades diferentes de elementos**, utilizando tf.add(). Mesmo o número de colunas sendo diferente do número de linhas, o somatório ocorre normalmente, contrariando a regra matemática de que a adição de matrizes só pode ser feita por matrizes de mesma ordem.

In [36]:
soma2 = tf.add(a2, b2)
print(a2.numpy())
print(b2.numpy())
print("---------------")
print(soma2.numpy())

[[1 2 3]
 [4 5 6]]
[[1]
 [2]]
---------------
[[2 3 4]
 [6 7 8]]


Utilizando o perador '+' obtêm-se o mesmo resultado do método tf.add()

In [37]:
print(a2 + b2)

tf.Tensor(
[[2 3 4]
 [6 7 8]], shape=(2, 3), dtype=int32)
